Revert "Disabled Chrome sandbox and enabled sudo in Travis CI"
This reverts commit e0d30a97a8795d97958cbf5c5fe550ec8e91d04f.

This commit caused deployment errors:

    Error: Cannot upload file [...], number of retries exceeded. Error: php_connect_nonb() failed: Operation now in progress (115) in vendor/dg/ftp-deployment/src/Deployment/FtpServer.php:118

This error is caused by ports being blocked by firewalls. See https://stackoverflow.com/questions/15688331/php-connect-nonb-failed-operation-now-in-progress-115-happens-intermitten